
[fields]
fromtiny = ' '
from = ' '
address = '''
.\\

'''
location = '. '
subject = '.'
opening = 'Dear Sir/Madam,'
content = '''
Please see the attachments for futher information.
'''
closing = 'Kind regards,'
name = '.'
signaturepath = '~/.signature.png'
