
[fields]
address = '''
<name/organization>\\
<street number> <street name>\\
<city>, <state zip code>\\
<COUNTRY>
'''
subject = ''
opening = 'Dear Sir/Madam,'
content = '''
Please see the attachments for futher information.
'''
closing = 'Kind regards,'
name = ''
signaturepath = '~/.config/LINKS/signature.png'
