
[fields]
address = '''
<name/organization>\\
<street number> <street name>\\
<city>, <state zip code>\\
<COUNTRY>
'''
subject = ''
opening = 'Greetings,'
content = '''
Please see the attachments for futher information.
'''
closing = 'Take care!'
name = ''
signaturepath = '~/.signature.png'
